# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {}

modules = []

doc_url = "https://linuxiscool.github.io/vanland_db/"

git_url = "https://github.com/linuxiscool/vanland_db/tree/master/"

def custom_doc_links(name): return None
